-- Criação do banco de dados "oficina"
CREATE DATABASE oficina;

-- Uso do banco de dados "oficina"
USE oficina;

-- Criação da tabela CLIENTE
CREATE TABLE CLIENTE (
  ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  ENDERECO VARCHAR(255),
  TELEFONE VARCHAR(20),
  EMAIL VARCHAR(50)
);

-- Criação da tabela VEICULO
CREATE TABLE VEICULO (
  ID_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
  PLACA VARCHAR(7) NOT NULL UNIQUE,
  MODELO VARCHAR(255) NOT NULL,
  ANO INT NOT NULL,
  COR VARCHAR(20),
  ID_CLIENTE INT NOT NULL,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Criação da tabela EQUIPE_MEC
CREATE TABLE EQUIPE_MEC (
  ID_EQUIPE_MEC INT PRIMARY KEY AUTO_INCREMENT,
  NOME_EQUIPE VARCHAR(255) NOT NULL
);

-- Criação da tabela MECANICO
CREATE TABLE MECANICO (
  ID_MECANICO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  ESPECIALIDADE VARCHAR(255),
  TELEFONE VARCHAR(20),
  ID_EQUIPE_MEC INT,
  FOREIGN KEY (ID_EQUIPE_MEC) REFERENCES EQUIPE_MEC(ID_EQUIPE_MEC)
);

-- Criação da tabela ORDEM_SERVICO
CREATE TABLE ORDEM_SERVICO (
  ID_OS INT PRIMARY KEY AUTO_INCREMENT,
  DATA_EMISSAO DATE NOT NULL,
  VALOR_TOTAL DECIMAL(10,2) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  ID_VEICULO INT NOT NULL,
  ID_EQUIPE_MEC INT NOT NULL,
  FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO),
  FOREIGN KEY (ID_EQUIPE_MEC) REFERENCES EQUIPE_MEC(ID_EQUIPE_MEC)
);

-- Criação da tabela ITEM_OS
CREATE TABLE ITEM_OS (
  ID_ITEM_OS INT PRIMARY KEY AUTO_INCREMENT,
  QUANTIDADE INT NOT NULL,
  SERVICO_REALIZADO VARCHAR(255) NOT NULL,
  ID_OS INT NOT NULL,
  ID_PEÇA INT,
  FOREIGN KEY (ID_OS) REFERENCES ORDEM_SERVICO(ID_OS),
  FOREIGN KEY (ID_PEÇA) REFERENCES PEÇA(ID_PEÇA)
);

-- Criação da tabela PEÇA
CREATE TABLE PEÇA (
  ID_PEÇA INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(255) NOT NULL,
  VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
  QUANTIDADE_ESTOQUE INT NOT NULL
);
